### ISSUE TITLE
Singleton. 

### ISSUE THREAD

**Issue by Pulpogrammer** [AlexMamo/FireApp#1]
Hi Alex, ask, what is the difference in having a @Singleton annotation in the authentication module? In this repository he did not use it you. 🤔

**Comment by AlexMamo** [comment]
Check this out: https://developer.android.com/training/dependency-injection/hilt-android#component-scopes

I used it here: https://github.com/alexmamo/FireApp/blob/master/app/src/main/java/ro/alexmamo/firebase/auth/AuthRepository.kt

**Comment by Pulpogrammer** [comment]
perfect Alex, now I understand, thank you very much! 👏👏
